[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6"
awc = "3.5.1"
dotenv = "0.15.0"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
tera = "1.20.0"
