[package]
name = "simple-api-web"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.72.0"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["macros"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
