[package]
name = "build_script"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.40"
thiserror = "2.0.11"

[build-dependencies]
cc = "1.2.10"

[dev-dependencies]
pretty_assertions = "1.4.1"
